### ISSUE TITLE
Feedback for “Getting Started with Airlytix: Connecting to WiFi”

### ISSUE THREAD

**Issue by chunter415** [Airlytix/docs#2]
I've just received 2 devices via online order and having difficulties installing Airlytix.  I've connected them to my computer, installed ESP home on them, connected them to wifi however there is no configuration.  I then to to install Airlytix to them via USB however each time they are failing.  Where am I going wrong on this?  Both devices are acting the same.  Thank you

**Comment by mikenorgate** [comment]
How did you install ESPHome on both devices? Did you do a fresh ESPHome install or just adopt the devices? Can you share what you see in the ESPHome dashboard.

Sometimes the install from the website has problems on some computers due to various security and web browser things

**Comment by chunter415** [comment]
I started with a fresh install of ESP home, going to esphome.io connected via google chrome and installed.  Then came over to Airlytix and attempted to install the newest version.  When I installed ESPHome I also got it connected to wifi and could browse to it, however none of the sensors where on it, thus installing Airlytix next.  When I connect via the web interface and try to install it gives me this message everytime.  I've tried multiple times.
Connecting via Chrome on Apple MBP.

<img width="1505" alt="Image" src="https://github.com/user-attachments/assets/00dd52ca-80b5-43b4-9bb9-b1b8d0568313" />

**Comment by mikenorgate** [comment]
By doing a fresh install of ESPHome you will have overridden the pre-installed setup that makes the Airlytix docs page work, this isn't really a problem though as the main purpose of that page is to get the device connected to your WiFi which you say you've already done.

In order to get all the sensors working you need to add the airlytix package into your ESPHome config so it looks something like this, then just flash this config over WiFi to the device

```
substitutions:
  name: airlytix-es1
  friendly_name: Airlytix
packages:
  airlytix.es1: github://airlytix/configuration/airlytix-es1.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: PUT_YOUR_ENCRYPTION_KEY_HERE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
